module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    USER_DATA:'user_info',
    GOOGLE_COLLECTION:'google_login',
    RATE_COLLECTION:'rating',
    CONTACT_COLLECTION:'contact_us'
}